ClinicaVivaEstetica.WebApp/Controllers/CustomersController.cs
using System;
using ClinicaVivaEstetica.WebApp.Models;
using ClinicaVivaEstetica.WebApp.Utils.RestIntegration;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ClinicaVivaEstetica.WebApp.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        public ActionResult Index()
        {
            var customers = RestIntegration.Get<ApiReturnList<CustomerResult>>("http://localhost:54878/", "/api/Customers");

            return View(customers?.Items);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerResult model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var result = RestIntegration.Post<CustomerResult, ApiReturnList<CustomerResult>>("http://localhost:54878/", "/api/Customers", model);

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }
            }
            catch(Exception e)
            {
                return View(model);
            }
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(Guid id)
        {
            var customer = RestIntegration.Get<ApiReturnItem<CustomerResult>>("http://localhost:54878/", $"/api/Customers/{id}");
            return View(customer?.Item);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerResult model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = RestIntegration.Put<CustomerResult, ApiReturnList<CustomerResult>>("http://localhost:54878/", "/api/Customers", model);

                    return RedirectToAction(nameof(Index));
                }

                return View(model);
            }
            catch (Exception e)
            {
                return View(model);
            }
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                var customer = RestIntegration.Delete("http://localhost:54878/", $"/api/Customers/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

ClinicaVivaEstetica.WebApp/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using ClinicaVivaEstetica.WebApp.Models;
using ClinicaVivaEstetica.WebApp.Utils.RestIntegration;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ClinicaVivaEstetica.WebApp.Controllers
{
    public class SchedulesController : Controller
    {
        // GET: Schedules
        public ActionResult Index()
        {
            var Schedules = RestIntegration.Get<ApiReturnList<ScheduleResult>>("http://localhost:54878/", "/api/Schedules");

            return View(Schedules?.Items);
        }

        // GET: Schedules/Create
        public ActionResult Create()
        {
            MakeDropdownsViewbags();
            return View();
        }

        // POST: Schedules/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ScheduleViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var validate = RestIntegration.Get<ApiReturnItem<Boolean>>("http://localhost:54878/", $"/api/Schedules/Validate/{model.Day.Value.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)}/{model.Hour}");

                    if (!(validate?.Item).GetValueOrDefault(false))
                    {
                        var result = RestIntegration.Post<ScheduleRequest, ApiReturnList<ScheduleResult>>(
                            "http://localhost:54878/", "/api/Schedules", new ScheduleRequest
                            {
                                Day = model.Day.Value,
                                Hour = model.Hour.Value,
                                ScheduleId = model.ScheduleId,
                                ServiceId = model.ServiceId,
                                CustomerId = model.CustomerId
                            });

                        return RedirectToAction(nameof(Index));
                    }

                    ModelState.AddModelError("Agendamento Existente", "Já existe agendamento no dia e horário escolhido");
                }

                MakeDropdownsViewbags();
                return View(model);

            }
            catch (Exception e)
            {
                MakeDropdownsViewbags(model.Hour, model.CustomerId, model.ServiceId);
                return View(model);
            }
        }

        // GET: Schedules/Edit/5
        public ActionResult Edit(Guid id)
        {
            var schedule = RestIntegration.Get<ApiReturnItem<ScheduleResult>>("http://localhost:54878/", $"/api/Schedules/{id}");

            MakeDropdownsViewbags(schedule?.Item?.Hour, schedule?.Item?.Customer?.CustomerId, schedule?.Item?.Service?.ServiceId);
            var model = schedule?.Item;

            return View(new ScheduleViewModel
            {
                Day = model.Day,
                Hour = model.Hour,
                ScheduleId = model.ScheduleId,
                ServiceId = model.ServiceId,
                CustomerId = model.CustomerId,
                Customer = model.Customer,
                Service = model.Service
            });
        }

        // POST: Schedules/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ScheduleViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var validate = RestIntegration.Get<ApiReturnItem<Boolean>>("http://localhost:54878/", $"/api/Schedules/Validate/{model.Day.Value:yyyy-MM-dd}/{model.Hour}/{model.ScheduleId}");

                    if (!(validate?.Item).GetValueOrDefault(false))
                    {
                        var result = RestIntegration.Put<ScheduleRequest, ApiReturnList<ScheduleResult>>(
                            "http://localhost:54878/", "/api/Schedules", new ScheduleRequest
                            {
                                Day = model.Day.Value,
                                Hour = model.Hour.Value,
                                ScheduleId = model.ScheduleId,
                                ServiceId = model.ServiceId,
                                CustomerId = model.CustomerId
                            });

                        return RedirectToAction(nameof(Index));
                    }

                    ModelState.AddModelError(String.Empty, "Já existe agendamento no dia e horário escolhido");
                }

                MakeDropdownsViewbags(model.Hour, model.CustomerId, model.ServiceId);
                return View(model);
            }
            catch (Exception e)
            {
                MakeDropdownsViewbags(model.Hour, model.CustomerId, model.ServiceId);
                return View(model);
            }
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                var Service = RestIntegration.Delete("http://localhost:54878/", $"/api/Schedules/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public void MakeDropdownsViewbags(TimeSpan? hour = null, Guid? customerId = null, Guid? serviceId = null)
        {
            ViewBag.Hours = MakeHoursDropDownList(hour);
            ViewBag.HalfHours = MakeHalfHoursDropDownList(hour);
            ViewBag.Customers = MakeCustomersDropDownList(customerId);
            ViewBag.Services = MakeServicesDropDownList(serviceId);
        }


        private IEnumerable<SelectListItem> MakeHoursDropDownList(TimeSpan? hour = null)
        {
            var listHours = new List<int>();
            for (int i = 8; i < 17; i++) listHours.Add(i);

            return listHours.Select(s => new SelectListItem
            {
                Text = s.ToString().PadLeft(2, '0') + ":00",
                Selected = hour.HasValue && hour == new TimeSpan(s, 0, 0),
                Value = new TimeSpan(s, 0, 0).ToString()
            });
        }

        private IEnumerable<SelectListItem> MakeHalfHoursDropDownList(TimeSpan? hour = null)
        {
            var listHours = new List<TimeSpan>();
            for (int i = 8; i < 17; i++)
            {
                listHours.Add(new TimeSpan(i, 0, 0));

                if (i != 16)
                    listHours.Add(new TimeSpan(i, 30, 0));
            }

            return listHours.Select(s => new SelectListItem
            {
                Text = s.ToString(@"hh\:mm"),
                Selected = hour.HasValue && hour == s,
                Value = s.ToString()
            });
        }

        private IEnumerable<SelectListItem> MakeCustomersDropDownList(Guid? customerId = null)
        {
            var customers = RestIntegration.Get<ApiReturnList<CustomerResult>>("http://localhost:54878/", "/api/Customers");
            return customers?.Items.Select(s => new SelectListItem
            {
                Text = s.Name,
                Selected = customerId.HasValue && s.CustomerId == customerId,
                Value = s.CustomerId.ToString()
            });
        }

        private IEnumerable<SelectListItem> MakeServicesDropDownList(Guid? serviceId = null)
        {
            var services = RestIntegration.Get<ApiReturnList<ServiceResult>>("http://localhost:54878/", "/api/Services");

            ViewBag.EntityServices = services?.Items ?? new List<ServiceResult>();

            return services?.Items.Select(s => new SelectListItem
            {
                Text = s.Name,
                Selected = serviceId.HasValue && s.ServiceId == serviceId,
                Value = s.ServiceId.ToString()
            });
        }
    }
}

ClinicaVivaEstetica.WebApp/Controllers/ServicesController.cs
using System;
using ClinicaVivaEstetica.WebApp.Models;
using ClinicaVivaEstetica.WebApp.Utils.RestIntegration;
using Microsoft.AspNetCore.Mvc;

namespace ClinicaVivaEstetica.WebApp.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Index()
        {
            var Services = RestIntegration.Get<ApiReturnList<ServiceResult>>("http://localhost:54878/", "/api/Services");

            return View(Services?.Items);
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ServiceResult model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var result = RestIntegration.Post<ServiceResult, ApiReturnList<ServiceResult>>("http://localhost:54878/", "/api/Services", model);

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }
            }
            catch(Exception e)
            {
                return View(model);
            }
        }

        // GET: Services/Edit/5
        public ActionResult Edit(Guid id)
        {
            var Service = RestIntegration.Get<ApiReturnItem<ServiceResult>>("http://localhost:54878/", $"/api/Services/{id}");
            return View(Service?.Item);
        }

        // POST: Services/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ServiceResult model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = RestIntegration.Put<ServiceResult, ApiReturnList<ServiceResult>>("http://localhost:54878/", "/api/Services", model);

                    return RedirectToAction(nameof(Index));
                }

                return View(model);
            }
            catch (Exception e)
            {
                return View(model);
            }
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                var Service = RestIntegration.Delete("http://localhost:54878/", $"/api/Services/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

ClinicaVivaEstetica.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clínica Viva Estética</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" />
</head>
<body onload="dvProgress.style.display = 'none';">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Clínica Viva Estética</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Customers" asp-action="Index">Clientes</a></li>
                    <li><a asp-area="" asp-controller="Services" asp-action="Index">Serviços</a></li>
                    <li><a asp-area="" asp-controller="Schedules" asp-action="Index">Agendamento</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div style="text-align: center; vertical-align: middle; font-family: Verdana; color: Blue;
                                      position: absolute; top: 50%; left: 50%; margin-left: -88px; font-size: small;"
             id="dvProgress" runat="server">
            <img src="~/images/ajax-loader.gif" style="vertical-align: middle" alt="Carregando" />
        </div>
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Clínica Viva Estética - Todos os direitos reservados.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-mask/dist/jquery.mask.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/lib/bootstrap-datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>
    @RenderSection("Scripts", required: false)


    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Confirma deleção?</h4>
                </div>
                <div class="modal-body">
                    Tem certeza que deseja deletar o registro selecionado?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-danger btn-primary btn-ok">Delete</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>